# -*- coding: utf-8 -*-
# @Time    : 2022/8/12 21:11
# @Author  : Mrli
# @File    : update_utils.py

# 老版本的提交数据
old_data = {
    "sfymqjczrj": "0",
    "sfyrjjh": "0",
    "nrjrq": "0",
    "sfqrxxss": "1",
    "sfqtyyqjwdg": "0",
    "sffrqjwdg": "0",
    "zgfx14rfh": "0",
    "sfyxjzxgym": "1",
    "sfbyjzrq": "5",
    "jzxgymqk": "2",
    "ismoved": "0",
    "tw": "0",
    "sfcxtz": "0",
    "sfjcbh": "0",
    "sfcxzysx": "0",
    "sfyyjc": "0",
    "jcjgqr": "0",
    "sfzx": "1",
    "sfjcwhry": "0",
    "sfjchbry": "0",
    "sfcyglq": "0",
    "sftjhb": "0",
    "sftjwh": "0",
    "sfyqjzgc": "0",
    "sfsqhzjkk": "1",
    "sqhzjkkys": "1",
    "szsqsfybl": "0",
    "sfygtjzzfj": "0",
    "dbfb7190a31b5f8cd4a85f5a4975b89b": "1651977968",
    "1a7c5b2e52854a2480947880eabe1fe1": "a3fefb4a32d22d9a3ff5827ac60bb1b0",
    "verifyCode": "var",
    "uid": "var",
    "id": "var",
    "date": "var",
    "created": "var",
    "address": "var",
    "geo_api_info": "var",
    "area": "var",
    "province": "var",
    "city": "var",
    "campus": "var",
}

# 新版本提交的数据, 在校外
old_data = {
    'sfymqjczrj': '0',
    'zjdfgj': '',
    'sfyrjjh': '0',
    'cfgj': '',
    'tjgj': '',
    'nrjrq': '0',
    'rjka': '',
    'jnmddsheng': '',
    'jnmddshi': '',
    'jnmddqu': '',
    'jnmddxiangxi': '',
    'rjjtfs': '',
    'rjjtfs1': '',
    'rjjtgjbc': '',
    'jnjtfs': '',
    'jnjtfs1': '',
    'jnjtgjbc': '',
    'sfqrxxss': '1',
    'sfqtyyqjwdg': '',
    'sffrqjwdg': '',
    'sfhsjc': '',
    'zgfx14rfh': '0',
    'zgfx14rfhdd': '',
    'sfyxjzxgym': '',
    'sfbyjzrq': '0',
    'jzxgymqk': '0',
    'campus': '',
    'ismoved': '5',
    'id': '53565980',
    'uid': '112775',
    'date': '20220811',
    'tw': '1',
    'sfcxtz': '0',
    'sfyyjc': '0',
    'jcjgqr': '0',
    'jcjg': '',
    'sfjcbh': '0',
    'sfcxzysx': '0',
    'remark': '',
    'address': '',
    'area': '浙江省 杭州市 西湖区',
    'province': '',
    'city': '',
    'geo_api_info': '{"type":"error","message":"Get ipLocation failed.Get geolocation failed.","info":"FAILED","status":0}',
    'created': '1660212822',
    'qksm': '',
    'sfzx': '0',
    'sfjcwhry': '0',
    'sfcyglq': '0',
    'gllx': '',
    'glksrq': '',
    'jcbhlx': '',
    'jcbhrq': '',
    'sftjwh': '0',
    'sftjhb': '0',
    'fxyy': '',
    'bztcyy': '',
    'fjsj': '0',
    'sfjchbry': '0',
    'jrsfqzys': '',
    'jrsfqzfy': '',
    'sfyqjzgc': '0',
    'jrdqjcqk': '',
    'sfjcqz': '',
    'jcqzrq': '',
    'jcwhryfs': '',
    'jchbryfs': '',
    'xjzd': '',
    'szgj': '',
    'sfsfbh': '0',
    'jhfjrq': '',
    'jhfjjtgj': '',
    'jhfjhbcc': '',
    'jhfjsftjwh': '0',
    'jhfjsftjhb': '0',
    'szsqsfybl': '0',
    'sfsqhzjkk': '0',
    'sqhzjkkys': '1',
    'sfygtjzzfj': '0',
    'gtjzzfjsj': '',
    'gwszgz': '',
    'gwszgzcs': '',
    'internship': '1',
    'gwszdd': '',
    'szgjcs': '',
    'verifyCode': '',
    '9762e6b13250f608aa783c82e3ee8a6d': '1660308807',
    '41083ff8603ce98eb2f32289850003ee': '2a4f29dc7e7454e7aa0165c99a1007ad',
    'zgfx14rfhsj': '',
}

# 新版本提交的数据, 在校
now_data = {
    'sfymqjczrj': '0',
    'zjdfgj': '',
    'sfyrjjh': '0',
    'cfgj': '',
    'tjgj': '',
    'nrjrq': '0',
    'rjka': '',
    'jnmddsheng': '',
    'jnmddshi': '',
    'jnmddqu': '',
    'jnmddxiangxi': '',
    'rjjtfs': '',
    'rjjtfs1': '',
    'rjjtgjbc': '',
    'jnjtfs': '',
    'jnjtfs1': '',
    'jnjtgjbc': '',
    'sfqrxxss': '1',
    'sfqtyyqjwdg': '',
    'sffrqjwdg': '',
    'sfhsjc': '',
    'zgfx14rfh': '0',
    'zgfx14rfhdd': '',
    'sfyxjzxgym': '',
    'sfbyjzrq': '0',
    'jzxgymqk': '0',
    'campus': '紫金港校区',
    'ismoved': '5',
    'id': '53565980',
    'uid': '112775',
    'date': '20220811',
    'tw': '0',
    'sfcxtz': '0',
    'sfyyjc': '0',
    'jcjgqr': '0',
    'jcjg': '',
    'sfjcbh': '0',
    'sfcxzysx': '0',
    'remark': '',
    'address': '',
    'area': '浙江省 杭州市 西湖区',
    'province': '',
    'city': '',
    'geo_api_info': '{"type":"error","message":"Get ipLocation failed.Get geolocation failed.","info":"FAILED","status":0}',
    'created': '1660212822',
    'qksm': '',
    'sfzx': '1',
    'sfjcwhry': '0',
    'sfcyglq': '0',
    'gllx': '',
    'glksrq': '',
    'jcbhlx': '',
    'jcbhrq': '',
    'sftjwh': '0',
    'sftjhb': '0',
    'fxyy': '',
    'bztcyy': '',
    'fjsj': '0',
    'sfjchbry': '0',
    'jrsfqzys': '',
    'jrsfqzfy': '',
    'sfyqjzgc': '0',
    'jrdqjcqk': '',
    'sfjcqz': '',
    'jcqzrq': '',
    'jcwhryfs': '',
    'jchbryfs': '',
    'xjzd': '',
    'szgj': '',
    'sfsfbh': '0',
    'jhfjrq': '',
    'jhfjjtgj': '',
    'jhfjhbcc': '',
    'jhfjsftjwh': '0',
    'jhfjsftjhb': '0',
    'szsqsfybl': '0',
    'sfsqhzjkk': '0',
    'sqhzjkkys': '5',
    'sfygtjzzfj': '0',
    'gtjzzfjsj': '',
    'gwszgz': '',
    'gwszgzcs': '',
    'internship': '1',
    'gwszdd': '',
    'szgjcs': '',
    'verifyCode': '',
    '9762e6b13250f608aa783c82e3ee8a6d': '1660308807',
    '41083ff8603ce98eb2f32289850003ee': '2a4f29dc7e7454e7aa0165c99a1007ad',
    'zgfx14rfhsj': '',
}


def copeFlagParam():
    ss = """
    "verifyCode": cope_with_captcha(self.sess),
    "uid": new_uid,
    "id": new_id,
    'date': get_date(),
    'created': round(time.time()),
    'address': formatted_address,
    'geo_api_info': geo_api_info_dict,
    'area': ew,
    'province': address_component.get("province"),
    'city': address_component.get("city"),
    "campus": campus,
    """
    import re
    pattern = '[\"\'](\w+)[\"\']: ?(.*?),\n'
    res = re.sub(pattern, '\"\\1\": \"var\",\n', ss)
    print(res)


def getDictIntersection(a, b):
    s1 = set(a.keys())
    s2 = set(b.keys())
    return s1.intersection(s2)


def getUpdatedInfo():
    """获得当前版本的参数有哪些改动"""
    print("\n**now_data 中新增的参数~: ")
    for k, v in now_data.items():
        if k not in old_data.keys():
            print(f"'{k}': '{v}',")

    print("\n**old_data 中删除的参数: ")
    for k, v in old_data.items():
        if k not in now_data.keys():
            print(f"'{k}': '{v}',")

    print("\n**更新的值有~: ")
    key_list = getDictIntersection(now_data, old_data)
    for k in key_list:
        if old_data.get(k) != now_data.get(k) and old_data.get(k) != "var":
            print(f"[k]: {k}\n\told: {old_data.get(k)}, now: {now_data.get(k)}")


if __name__ == '__main__':
    # copeFlagParam()
    getUpdatedInfo()
